// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx_GfAJMViA3GflW5ose_-xESiZAihfCI',
    appId: '1:119146063357:web:54cabde3a438d43520e594',
    messagingSenderId: '119146063357',
    projectId: 'flutter-authen-bd252',
    authDomain: 'flutter-authen-bd252.firebaseapp.com',
    storageBucket: 'flutter-authen-bd252.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnO2uxHFmrXcIpy73031Y8XBSt-PnDugg',
    appId: '1:119146063357:android:4df81aeb6e1d8a7f20e594',
    messagingSenderId: '119146063357',
    projectId: 'flutter-authen-bd252',
    storageBucket: 'flutter-authen-bd252.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8h0lGf2uXccB5BnAdS4d5Ztk4GHdOACQ',
    appId: '1:119146063357:ios:21b68073211c324f20e594',
    messagingSenderId: '119146063357',
    projectId: 'flutter-authen-bd252',
    storageBucket: 'flutter-authen-bd252.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuthen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8h0lGf2uXccB5BnAdS4d5Ztk4GHdOACQ',
    appId: '1:119146063357:ios:21b68073211c324f20e594',
    messagingSenderId: '119146063357',
    projectId: 'flutter-authen-bd252',
    storageBucket: 'flutter-authen-bd252.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuthen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx_GfAJMViA3GflW5ose_-xESiZAihfCI',
    appId: '1:119146063357:web:8ddd9866fe4e983420e594',
    messagingSenderId: '119146063357',
    projectId: 'flutter-authen-bd252',
    authDomain: 'flutter-authen-bd252.firebaseapp.com',
    storageBucket: 'flutter-authen-bd252.firebasestorage.app',
  );

}